[Icon Theme]
Name=glabels-vector
Comment=gLabels vector icon theme (light)
Inherits=glabels-flat,hicolor
Directories=16x16/actions,22x22/actions,24x24/actions,32x32/actions,48x48/actions


[16x16/actions]
Size=16
Type=Fixed
Context=Actions

[22x22/actions]
Size=22
Type=Fixed
Context=Actions

[24x24/actions]
Size=24
Type=Fixed
Context=Actions

[32x32/actions]
Size=32
Type=Fixed
Context=Actions

[48x48/actions]
Size=48
Type=Fixed
Context=Actions
